// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RT.Contacts.DataAccess.Concrete;

#nullable disable

namespace RT.Contacts.DataAccess.Migrations
{
    [DbContext(typeof(PostgreSqlEfDbContext))]
    [Migration("20220701200758_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RT.Contacts.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UUID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firma")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UUID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("RT.Contacts.Domain.Entities.Contact", b =>
                {
                    b.OwnsMany("RT.Contacts.Domain.Entities.ContactDetail", "IletisimBilgileri", b1 =>
                        {
                            b1.Property<int>("ContactUUID")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("BilgiIcerigi")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("BilgiTipi")
                                .HasColumnType("integer");

                            b1.HasKey("ContactUUID", "Id");

                            b1.ToTable("ContactDetails");

                            b1.WithOwner()
                                .HasForeignKey("ContactUUID");
                        });

                    b.Navigation("IletisimBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
